export const configuration = {
  "animations": true,
  "colorScheme": {
    "name": "cool",
    "selectable": true,
    "group": "ordinal",
    "domain": [
      "#a8385d",
      "#7aa3e5",
      "#a27ea8",
      "#aae3f5",
      "#adcded",
      "#a95963",
      "#8796c0",
      "#7ed3ed",
      "#50abcc",
      "#ad6886"
    ]
  },
  "schemeType": "ordinal",
  "showXAxis": true,
  "showYAxis": true,
  "gradient": false,
  "barPadding": 8,
  "noBarWhenZero": true,
  "showLegend": true,
  "legendTitle": "LegendASDASDASD",
  "legendPosition": "right",
  "showXAxisLabel": true,
  "xAxisLabel": "Country",
  "showYAxisLabel": true,
  "yAxisLabel": "GDP Per Capita",
  "showGridLines": true,
  "roundDomains": false,
  "tooltipDisabled": false,
  "roundEdges": true,
  "showDataLabel": false,
  "trimXAxisTicks": true,
  "trimYAxisTicks": true,
  "rotateXAxisTicks": true,
  "maxXAxisTickLength": 16,
  "maxYAxisTickLength": 16
}
